// This file was auto-generated by figma_flutter_gen
// Do not edit this file manually
// Application color constants generated from Figma variables
//
// Generated on: 2025-08-22T15:21:21.321752

import 'package:flutter/material.dart';

/// Application color constants
/// Generated from Figma design tokens
class AppColors {
  AppColors._();

  // MODE 1 MODE COLORS
  /// No description
  static const Color mode1TextColorTextBase = Color(0xFF101828);

  /// No description
  static const Color mode1TextColorText = Color(0xFF252B37);

  /// No description
  static const Color mode1TextColorTextTertiary = Color(0xFF252B37);

  /// No description
  static const Color mode1TextColorTextLightSolid = Color(0xFFFFFFFF);

  /// No description
  static const Color mode1TextColorTextDisabled = Color(0xFFE9EAEB);

  /// No description
  static const Color mode1TextColorTextPlaceholder = Color(0xFFD5D7DA);

  /// No description
  static const Color mode1TextColorTextSecondary = Color(0xFF717680);

  /// No description
  static const Color mode1TextColorTextDescription = Color(0xFFAFB5D9);

  /// No description
  static const Color mode1IconColorIcon = Color(0xFFAF34F8);

  /// No description
  static const Color mode1BackgroundColorBgContainer = Color(0xFFF5F5F7);

  /// No description
  static const Color mode1BackgroundColorBgBase = Color(0xFFFFFFFF);

  /// No description
  static const Color mode1BorderColorSplit = Color(0xFFEAECF5);

  /// No description
  static const Color mode1BorderColorBorderSecondary = Color(0xFFD5D9EB);

  /// No description
  static const Color mode1BorderColorBorder = Color(0xFFD8D8E0);

  /// No description
  static const Color mode1FillColorFillTertiary = Color(0xFFD5D9EB);

  /// No description
  static const Color mode1FillColorFillSecondary = Color(0xFFF8F9FC);

  /// No description
  static const Color mode1FillColorFill = Color(0xFFFFFFFF);

  /// No description
  static const Color mode1PrimaryColorPrimaryTextActive = Color(0xFF5A0A8A);

  /// No description
  static const Color mode1PrimaryColorPrimary = Color(0xFFAF34F8);

  /// No description
  static const Color mode1PrimaryColorPrimaryBg = Color(0xFFF7E8FF);

  /// No description
  static const Color mode1PrimaryColorPrimaryActive = Color(0xFF710BAE);

  /// No description
  static const Color mode1PrimaryColorPrimaryBorder = Color(0xFFE6BCFF);

  /// No description
  static const Color mode1PrimaryColorPrimaryText = Color(0xFF710BAE);

  /// No description
  static const Color mode1IconColorIconSecondary = Color(0xFF5A0A8A);

  /// No description
  static const Color mode1SecondaryColorSecondaryBg = Color(0xFFFCFCFD);

  /// No description
  static const Color mode1SecondaryColorSecondaryBorder = Color(0xFFAFB5D9);

  /// No description
  static const Color mode1SecondaryColorSecondary = Color(0xFF293056);

  /// No description
  static const Color mode1SuccessColorSuccess = Color(0xFF039855);

  /// No description
  static const Color mode1SuccessColorSuccessText = Color(0xFF12B76A);

  /// No description
  static const Color mode1SuccessColorSuccessBorder = Color(0xFF32D583);

  /// No description
  static const Color mode1SuccessColorSuccessBg = Color(0xFFF6FEF9);

  /// No description
  static const Color mode1LinkColorLinkActive = Color(0xFF0086C9);

  /// No description
  static const Color mode1LinkColorLink = Color(0xFF0BA5EC);

  /// No description
  static const Color mode1WarningColorWarning = Color(0xFFF79009);

  /// No description
  static const Color mode1WarningColorWarningBorder = Color(0xFFFDB022);

  /// No description
  static const Color mode1WarningColorWarningText = Color(0xFFDC6803);

  /// No description
  static const Color mode1WarningColorWarningBg = Color(0xFFFFFCF5);

  /// No description
  static const Color mode1ErrorColorErrorText = Color(0xFFD92D20);

  /// No description
  static const Color mode1ErrorColorErrorBorder = Color(0xFFF97066);

  /// No description
  static const Color mode1ErrorColorError = Color(0xFFF04438);

  /// No description
  static const Color mode1ErrorColorErrorBg = Color(0xFFFFFBFA);

  /// Get all available color modes
  static const List<String> availableModes = ['Mode 1'];

  /// Mode 1 mode color map
  static const Map<String, Color> mode1Colors = {
    'Text/colorTextBase': mode1TextColorTextBase,
    'Text/colorText': mode1TextColorText,
    'Text/colorTextTertiary': mode1TextColorTextTertiary,
    'Text/colorTextLightSolid': mode1TextColorTextLightSolid,
    'Text/colorTextDisabled': mode1TextColorTextDisabled,
    'Text/colorTextPlaceholder': mode1TextColorTextPlaceholder,
    'Text/colorTextSecondary': mode1TextColorTextSecondary,
    'Text/colorTextDescription': mode1TextColorTextDescription,
    'Icon/colorIcon': mode1IconColorIcon,
    'Background/colorBgContainer': mode1BackgroundColorBgContainer,
    'Background/colorBgBase': mode1BackgroundColorBgBase,
    'Border/colorSplit': mode1BorderColorSplit,
    'Border/colorBorderSecondary': mode1BorderColorBorderSecondary,
    'Border/colorBorder': mode1BorderColorBorder,
    'Fill/colorFillTertiary': mode1FillColorFillTertiary,
    'Fill/colorFillSecondary': mode1FillColorFillSecondary,
    'Fill/colorFill': mode1FillColorFill,
    'Primary/colorPrimaryTextActive': mode1PrimaryColorPrimaryTextActive,
    'Primary/colorPrimary': mode1PrimaryColorPrimary,
    'Primary/colorPrimaryBg': mode1PrimaryColorPrimaryBg,
    'Primary/colorPrimaryActive': mode1PrimaryColorPrimaryActive,
    'Primary/colorPrimaryBorder': mode1PrimaryColorPrimaryBorder,
    'Primary/colorPrimaryText': mode1PrimaryColorPrimaryText,
    'Icon/colorIconSecondary': mode1IconColorIconSecondary,
    'Secondary/colorSecondaryBg': mode1SecondaryColorSecondaryBg,
    'Secondary/colorSecondaryBorder': mode1SecondaryColorSecondaryBorder,
    'Secondary/colorSecondary': mode1SecondaryColorSecondary,
    'Success/colorSuccess': mode1SuccessColorSuccess,
    'Success/colorSuccessText': mode1SuccessColorSuccessText,
    'Success/colorSuccessBorder': mode1SuccessColorSuccessBorder,
    'Success/colorSuccessBg': mode1SuccessColorSuccessBg,
    'Link/colorLinkActive': mode1LinkColorLinkActive,
    'Link/colorLink': mode1LinkColorLink,
    'Warning/colorWarning': mode1WarningColorWarning,
    'Warning/colorWarningBorder': mode1WarningColorWarningBorder,
    'Warning/colorWarningText': mode1WarningColorWarningText,
    'Warning/colorWarningBg': mode1WarningColorWarningBg,
    'Error/colorErrorText': mode1ErrorColorErrorText,
    'Error/colorErrorBorder': mode1ErrorColorErrorBorder,
    'Error/colorError': mode1ErrorColorError,
    'Error/colorErrorBg': mode1ErrorColorErrorBg,
  };

  /// Get color by variable name and mode
  static Color? getColor(String variableName, [String mode = "Light"]) {
    switch (mode) {
      case 'Mode 1':
        return mode1Colors[variableName];
      default:
        return mode1Colors[variableName];
    }
  }
}
