// This file was auto-generated by figma_flutter_gen
// Do not edit this file manually
// Application theme configuration generated from Figma variables
//
// Generated on: 2025-08-22T15:21:21.485767

import 'package:flutter/material.dart';
import 'custom_colors.dart';

/// Pre-configured theme instances with CustomColors extensions applied.
/// Use these theme instances directly in your MaterialApp.
class AppTheme {
  AppTheme._();

  /// Mode 1 theme with CustomColors extension.
  static final ThemeData mode1 = ThemeData(
    useMaterial3: true,
    brightness: Brightness.light,
    colorScheme: ColorScheme.light(),
    extensions: <ThemeExtension<dynamic>>[CustomColors.mode1Theme],
  );

  /// Get all available theme modes.
  static Map<String, ThemeData> get allThemes => {'Mode 1': mode1};

  /// Get theme by mode name.
  static ThemeData? getThemeByMode(String mode) {
    return allThemes[mode];
  }

  /// Get all available mode names.
  static List<String> get availableModes => ['Mode 1'];

  /// Check if a mode is considered light theme.
  static bool isLightMode(String mode) {
    return mode.toLowerCase() == 'light';
  }

  /// Get appropriate theme based on system brightness.
  static ThemeData getAdaptiveTheme(Brightness brightness) {
    switch (brightness) {
      case Brightness.light:
        return mode1;
      case Brightness.dark:
        return mode1;
    }
  }
}
