// This file was auto-generated by figma_flutter_gen
// Do not edit this file manually
// Custom colors theme extension generated from Figma variables
//
// Generated on: 2025-08-22T15:21:21.434207

import 'package:flutter/material.dart';
import 'app_colors.dart';

/// Custom colors theme extension
/// Provides access to Figma design system colors through theme context
class CustomColors extends ThemeExtension<CustomColors> {
  const CustomColors({
    this.textColorTextBase,
    this.textColorText,
    this.textColorTextTertiary,
    this.textColorTextLightSolid,
    this.textColorTextDisabled,
    this.textColorTextPlaceholder,
    this.textColorTextSecondary,
    this.textColorTextDescription,
    this.iconColorIcon,
    this.backgroundColorBgContainer,
    this.backgroundColorBgBase,
    this.borderColorSplit,
    this.borderColorBorderSecondary,
    this.borderColorBorder,
    this.fillColorFillTertiary,
    this.fillColorFillSecondary,
    this.fillColorFill,
    this.primaryColorPrimaryTextActive,
    this.primaryColorPrimary,
    this.primaryColorPrimaryBg,
    this.primaryColorPrimaryActive,
    this.primaryColorPrimaryBorder,
    this.primaryColorPrimaryText,
    this.iconColorIconSecondary,
    this.secondaryColorSecondaryBg,
    this.secondaryColorSecondaryBorder,
    this.secondaryColorSecondary,
    this.successColorSuccess,
    this.successColorSuccessText,
    this.successColorSuccessBorder,
    this.successColorSuccessBg,
    this.linkColorLinkActive,
    this.linkColorLink,
    this.warningColorWarning,
    this.warningColorWarningBorder,
    this.warningColorWarningText,
    this.warningColorWarningBg,
    this.errorColorErrorText,
    this.errorColorErrorBorder,
    this.errorColorError,
    this.errorColorErrorBg,
  });

  /// No description
  final Color? textColorTextBase;

  /// No description
  final Color? textColorText;

  /// No description
  final Color? textColorTextTertiary;

  /// No description
  final Color? textColorTextLightSolid;

  /// No description
  final Color? textColorTextDisabled;

  /// No description
  final Color? textColorTextPlaceholder;

  /// No description
  final Color? textColorTextSecondary;

  /// No description
  final Color? textColorTextDescription;

  /// No description
  final Color? iconColorIcon;

  /// No description
  final Color? backgroundColorBgContainer;

  /// No description
  final Color? backgroundColorBgBase;

  /// No description
  final Color? borderColorSplit;

  /// No description
  final Color? borderColorBorderSecondary;

  /// No description
  final Color? borderColorBorder;

  /// No description
  final Color? fillColorFillTertiary;

  /// No description
  final Color? fillColorFillSecondary;

  /// No description
  final Color? fillColorFill;

  /// No description
  final Color? primaryColorPrimaryTextActive;

  /// No description
  final Color? primaryColorPrimary;

  /// No description
  final Color? primaryColorPrimaryBg;

  /// No description
  final Color? primaryColorPrimaryActive;

  /// No description
  final Color? primaryColorPrimaryBorder;

  /// No description
  final Color? primaryColorPrimaryText;

  /// No description
  final Color? iconColorIconSecondary;

  /// No description
  final Color? secondaryColorSecondaryBg;

  /// No description
  final Color? secondaryColorSecondaryBorder;

  /// No description
  final Color? secondaryColorSecondary;

  /// No description
  final Color? successColorSuccess;

  /// No description
  final Color? successColorSuccessText;

  /// No description
  final Color? successColorSuccessBorder;

  /// No description
  final Color? successColorSuccessBg;

  /// No description
  final Color? linkColorLinkActive;

  /// No description
  final Color? linkColorLink;

  /// No description
  final Color? warningColorWarning;

  /// No description
  final Color? warningColorWarningBorder;

  /// No description
  final Color? warningColorWarningText;

  /// No description
  final Color? warningColorWarningBg;

  /// No description
  final Color? errorColorErrorText;

  /// No description
  final Color? errorColorErrorBorder;

  /// No description
  final Color? errorColorError;

  /// No description
  final Color? errorColorErrorBg;

  /// Mode 1 theme colors
  static const mode1Theme = CustomColors(
    textColorTextBase: AppColors.mode1TextColorTextBase,
    textColorText: AppColors.mode1TextColorText,
    textColorTextTertiary: AppColors.mode1TextColorTextTertiary,
    textColorTextLightSolid: AppColors.mode1TextColorTextLightSolid,
    textColorTextDisabled: AppColors.mode1TextColorTextDisabled,
    textColorTextPlaceholder: AppColors.mode1TextColorTextPlaceholder,
    textColorTextSecondary: AppColors.mode1TextColorTextSecondary,
    textColorTextDescription: AppColors.mode1TextColorTextDescription,
    iconColorIcon: AppColors.mode1IconColorIcon,
    backgroundColorBgContainer: AppColors.mode1BackgroundColorBgContainer,
    backgroundColorBgBase: AppColors.mode1BackgroundColorBgBase,
    borderColorSplit: AppColors.mode1BorderColorSplit,
    borderColorBorderSecondary: AppColors.mode1BorderColorBorderSecondary,
    borderColorBorder: AppColors.mode1BorderColorBorder,
    fillColorFillTertiary: AppColors.mode1FillColorFillTertiary,
    fillColorFillSecondary: AppColors.mode1FillColorFillSecondary,
    fillColorFill: AppColors.mode1FillColorFill,
    primaryColorPrimaryTextActive: AppColors.mode1PrimaryColorPrimaryTextActive,
    primaryColorPrimary: AppColors.mode1PrimaryColorPrimary,
    primaryColorPrimaryBg: AppColors.mode1PrimaryColorPrimaryBg,
    primaryColorPrimaryActive: AppColors.mode1PrimaryColorPrimaryActive,
    primaryColorPrimaryBorder: AppColors.mode1PrimaryColorPrimaryBorder,
    primaryColorPrimaryText: AppColors.mode1PrimaryColorPrimaryText,
    iconColorIconSecondary: AppColors.mode1IconColorIconSecondary,
    secondaryColorSecondaryBg: AppColors.mode1SecondaryColorSecondaryBg,
    secondaryColorSecondaryBorder: AppColors.mode1SecondaryColorSecondaryBorder,
    secondaryColorSecondary: AppColors.mode1SecondaryColorSecondary,
    successColorSuccess: AppColors.mode1SuccessColorSuccess,
    successColorSuccessText: AppColors.mode1SuccessColorSuccessText,
    successColorSuccessBorder: AppColors.mode1SuccessColorSuccessBorder,
    successColorSuccessBg: AppColors.mode1SuccessColorSuccessBg,
    linkColorLinkActive: AppColors.mode1LinkColorLinkActive,
    linkColorLink: AppColors.mode1LinkColorLink,
    warningColorWarning: AppColors.mode1WarningColorWarning,
    warningColorWarningBorder: AppColors.mode1WarningColorWarningBorder,
    warningColorWarningText: AppColors.mode1WarningColorWarningText,
    warningColorWarningBg: AppColors.mode1WarningColorWarningBg,
    errorColorErrorText: AppColors.mode1ErrorColorErrorText,
    errorColorErrorBorder: AppColors.mode1ErrorColorErrorBorder,
    errorColorError: AppColors.mode1ErrorColorError,
    errorColorErrorBg: AppColors.mode1ErrorColorErrorBg,
  );

  @override
  CustomColors copyWith({
    Color? textColorTextBase,
    Color? textColorText,
    Color? textColorTextTertiary,
    Color? textColorTextLightSolid,
    Color? textColorTextDisabled,
    Color? textColorTextPlaceholder,
    Color? textColorTextSecondary,
    Color? textColorTextDescription,
    Color? iconColorIcon,
    Color? backgroundColorBgContainer,
    Color? backgroundColorBgBase,
    Color? borderColorSplit,
    Color? borderColorBorderSecondary,
    Color? borderColorBorder,
    Color? fillColorFillTertiary,
    Color? fillColorFillSecondary,
    Color? fillColorFill,
    Color? primaryColorPrimaryTextActive,
    Color? primaryColorPrimary,
    Color? primaryColorPrimaryBg,
    Color? primaryColorPrimaryActive,
    Color? primaryColorPrimaryBorder,
    Color? primaryColorPrimaryText,
    Color? iconColorIconSecondary,
    Color? secondaryColorSecondaryBg,
    Color? secondaryColorSecondaryBorder,
    Color? secondaryColorSecondary,
    Color? successColorSuccess,
    Color? successColorSuccessText,
    Color? successColorSuccessBorder,
    Color? successColorSuccessBg,
    Color? linkColorLinkActive,
    Color? linkColorLink,
    Color? warningColorWarning,
    Color? warningColorWarningBorder,
    Color? warningColorWarningText,
    Color? warningColorWarningBg,
    Color? errorColorErrorText,
    Color? errorColorErrorBorder,
    Color? errorColorError,
    Color? errorColorErrorBg,
  }) {
    return CustomColors(
      textColorTextBase: textColorTextBase ?? this.textColorTextBase,
      textColorText: textColorText ?? this.textColorText,
      textColorTextTertiary:
          textColorTextTertiary ?? this.textColorTextTertiary,
      textColorTextLightSolid:
          textColorTextLightSolid ?? this.textColorTextLightSolid,
      textColorTextDisabled:
          textColorTextDisabled ?? this.textColorTextDisabled,
      textColorTextPlaceholder:
          textColorTextPlaceholder ?? this.textColorTextPlaceholder,
      textColorTextSecondary:
          textColorTextSecondary ?? this.textColorTextSecondary,
      textColorTextDescription:
          textColorTextDescription ?? this.textColorTextDescription,
      iconColorIcon: iconColorIcon ?? this.iconColorIcon,
      backgroundColorBgContainer:
          backgroundColorBgContainer ?? this.backgroundColorBgContainer,
      backgroundColorBgBase:
          backgroundColorBgBase ?? this.backgroundColorBgBase,
      borderColorSplit: borderColorSplit ?? this.borderColorSplit,
      borderColorBorderSecondary:
          borderColorBorderSecondary ?? this.borderColorBorderSecondary,
      borderColorBorder: borderColorBorder ?? this.borderColorBorder,
      fillColorFillTertiary:
          fillColorFillTertiary ?? this.fillColorFillTertiary,
      fillColorFillSecondary:
          fillColorFillSecondary ?? this.fillColorFillSecondary,
      fillColorFill: fillColorFill ?? this.fillColorFill,
      primaryColorPrimaryTextActive:
          primaryColorPrimaryTextActive ?? this.primaryColorPrimaryTextActive,
      primaryColorPrimary: primaryColorPrimary ?? this.primaryColorPrimary,
      primaryColorPrimaryBg:
          primaryColorPrimaryBg ?? this.primaryColorPrimaryBg,
      primaryColorPrimaryActive:
          primaryColorPrimaryActive ?? this.primaryColorPrimaryActive,
      primaryColorPrimaryBorder:
          primaryColorPrimaryBorder ?? this.primaryColorPrimaryBorder,
      primaryColorPrimaryText:
          primaryColorPrimaryText ?? this.primaryColorPrimaryText,
      iconColorIconSecondary:
          iconColorIconSecondary ?? this.iconColorIconSecondary,
      secondaryColorSecondaryBg:
          secondaryColorSecondaryBg ?? this.secondaryColorSecondaryBg,
      secondaryColorSecondaryBorder:
          secondaryColorSecondaryBorder ?? this.secondaryColorSecondaryBorder,
      secondaryColorSecondary:
          secondaryColorSecondary ?? this.secondaryColorSecondary,
      successColorSuccess: successColorSuccess ?? this.successColorSuccess,
      successColorSuccessText:
          successColorSuccessText ?? this.successColorSuccessText,
      successColorSuccessBorder:
          successColorSuccessBorder ?? this.successColorSuccessBorder,
      successColorSuccessBg:
          successColorSuccessBg ?? this.successColorSuccessBg,
      linkColorLinkActive: linkColorLinkActive ?? this.linkColorLinkActive,
      linkColorLink: linkColorLink ?? this.linkColorLink,
      warningColorWarning: warningColorWarning ?? this.warningColorWarning,
      warningColorWarningBorder:
          warningColorWarningBorder ?? this.warningColorWarningBorder,
      warningColorWarningText:
          warningColorWarningText ?? this.warningColorWarningText,
      warningColorWarningBg:
          warningColorWarningBg ?? this.warningColorWarningBg,
      errorColorErrorText: errorColorErrorText ?? this.errorColorErrorText,
      errorColorErrorBorder:
          errorColorErrorBorder ?? this.errorColorErrorBorder,
      errorColorError: errorColorError ?? this.errorColorError,
      errorColorErrorBg: errorColorErrorBg ?? this.errorColorErrorBg,
    );
  }

  @override
  CustomColors lerp(ThemeExtension<CustomColors>? other, double t) {
    if (other is! CustomColors) return this;
    return CustomColors(
      textColorTextBase: Color.lerp(
        textColorTextBase,
        other.textColorTextBase,
        t,
      ),
      textColorText: Color.lerp(textColorText, other.textColorText, t),
      textColorTextTertiary: Color.lerp(
        textColorTextTertiary,
        other.textColorTextTertiary,
        t,
      ),
      textColorTextLightSolid: Color.lerp(
        textColorTextLightSolid,
        other.textColorTextLightSolid,
        t,
      ),
      textColorTextDisabled: Color.lerp(
        textColorTextDisabled,
        other.textColorTextDisabled,
        t,
      ),
      textColorTextPlaceholder: Color.lerp(
        textColorTextPlaceholder,
        other.textColorTextPlaceholder,
        t,
      ),
      textColorTextSecondary: Color.lerp(
        textColorTextSecondary,
        other.textColorTextSecondary,
        t,
      ),
      textColorTextDescription: Color.lerp(
        textColorTextDescription,
        other.textColorTextDescription,
        t,
      ),
      iconColorIcon: Color.lerp(iconColorIcon, other.iconColorIcon, t),
      backgroundColorBgContainer: Color.lerp(
        backgroundColorBgContainer,
        other.backgroundColorBgContainer,
        t,
      ),
      backgroundColorBgBase: Color.lerp(
        backgroundColorBgBase,
        other.backgroundColorBgBase,
        t,
      ),
      borderColorSplit: Color.lerp(borderColorSplit, other.borderColorSplit, t),
      borderColorBorderSecondary: Color.lerp(
        borderColorBorderSecondary,
        other.borderColorBorderSecondary,
        t,
      ),
      borderColorBorder: Color.lerp(
        borderColorBorder,
        other.borderColorBorder,
        t,
      ),
      fillColorFillTertiary: Color.lerp(
        fillColorFillTertiary,
        other.fillColorFillTertiary,
        t,
      ),
      fillColorFillSecondary: Color.lerp(
        fillColorFillSecondary,
        other.fillColorFillSecondary,
        t,
      ),
      fillColorFill: Color.lerp(fillColorFill, other.fillColorFill, t),
      primaryColorPrimaryTextActive: Color.lerp(
        primaryColorPrimaryTextActive,
        other.primaryColorPrimaryTextActive,
        t,
      ),
      primaryColorPrimary: Color.lerp(
        primaryColorPrimary,
        other.primaryColorPrimary,
        t,
      ),
      primaryColorPrimaryBg: Color.lerp(
        primaryColorPrimaryBg,
        other.primaryColorPrimaryBg,
        t,
      ),
      primaryColorPrimaryActive: Color.lerp(
        primaryColorPrimaryActive,
        other.primaryColorPrimaryActive,
        t,
      ),
      primaryColorPrimaryBorder: Color.lerp(
        primaryColorPrimaryBorder,
        other.primaryColorPrimaryBorder,
        t,
      ),
      primaryColorPrimaryText: Color.lerp(
        primaryColorPrimaryText,
        other.primaryColorPrimaryText,
        t,
      ),
      iconColorIconSecondary: Color.lerp(
        iconColorIconSecondary,
        other.iconColorIconSecondary,
        t,
      ),
      secondaryColorSecondaryBg: Color.lerp(
        secondaryColorSecondaryBg,
        other.secondaryColorSecondaryBg,
        t,
      ),
      secondaryColorSecondaryBorder: Color.lerp(
        secondaryColorSecondaryBorder,
        other.secondaryColorSecondaryBorder,
        t,
      ),
      secondaryColorSecondary: Color.lerp(
        secondaryColorSecondary,
        other.secondaryColorSecondary,
        t,
      ),
      successColorSuccess: Color.lerp(
        successColorSuccess,
        other.successColorSuccess,
        t,
      ),
      successColorSuccessText: Color.lerp(
        successColorSuccessText,
        other.successColorSuccessText,
        t,
      ),
      successColorSuccessBorder: Color.lerp(
        successColorSuccessBorder,
        other.successColorSuccessBorder,
        t,
      ),
      successColorSuccessBg: Color.lerp(
        successColorSuccessBg,
        other.successColorSuccessBg,
        t,
      ),
      linkColorLinkActive: Color.lerp(
        linkColorLinkActive,
        other.linkColorLinkActive,
        t,
      ),
      linkColorLink: Color.lerp(linkColorLink, other.linkColorLink, t),
      warningColorWarning: Color.lerp(
        warningColorWarning,
        other.warningColorWarning,
        t,
      ),
      warningColorWarningBorder: Color.lerp(
        warningColorWarningBorder,
        other.warningColorWarningBorder,
        t,
      ),
      warningColorWarningText: Color.lerp(
        warningColorWarningText,
        other.warningColorWarningText,
        t,
      ),
      warningColorWarningBg: Color.lerp(
        warningColorWarningBg,
        other.warningColorWarningBg,
        t,
      ),
      errorColorErrorText: Color.lerp(
        errorColorErrorText,
        other.errorColorErrorText,
        t,
      ),
      errorColorErrorBorder: Color.lerp(
        errorColorErrorBorder,
        other.errorColorErrorBorder,
        t,
      ),
      errorColorError: Color.lerp(errorColorError, other.errorColorError, t),
      errorColorErrorBg: Color.lerp(
        errorColorErrorBg,
        other.errorColorErrorBg,
        t,
      ),
    );
  }
}

/// Extension on [ThemeData] to access custom colors
extension CustomColorsExtension on ThemeData {
  /// Get custom colors from theme
  CustomColors? get customColors => extension<CustomColors>();
}

/// Extension on [BuildContext] to access custom colors
extension CustomColorsBuildContext on BuildContext {
  /// Get custom colors from theme
  CustomColors? get customColors => Theme.of(this).extension<CustomColors>();
}
